Vagrant.configure("2") do |config|
  nodes = {
    "k8s-master" => { cpus: 2, memory: 4096 },
    "k8s-worker1" => { cpus: 2, memory: 4096 },
    "k8s-worker2" => { cpus: 2, memory: 4096 }
  }

  nodes.each do |hostname, options|
    config.vm.define hostname do |node|
      node.vm.box = "almalinux/9"
      node.vm.hostname = hostname
      node.vm.network "private_network", type: "dhcp"

      node.vm.provider "vmware_desktop" do |v|
        v.vmx["memsize"] = options[:memory]
        v.vmx["numvcpus"] = options[:cpus]
      end
    end
  end
end
